### ISSUE TITLE
from __future__ import annotations only available >=3.7

### ISSUE THREAD

**Issue by BastianZim** [instacart/arn#11]
Hi,
the following line https://github.com/instacart/arn/blob/d4b1362ae81c087287b7f8f39fee328248109ebf/src/arn/__init__.py#L1 is only available starting with `python3.7` as can be seen [here](https://www.python.org/dev/peps/pep-0563/#enabling-the-future-behavior-in-python-3-7), whilst the package is available starting 3.6 as is defined here: https://github.com/instacart/arn/blob/d4b1362ae81c087287b7f8f39fee328248109ebf/setup.py#L18
Is that a bug or should we assume the code to only be available starting 3.7?
Thanks!

**Comment by francoiscampbell** [comment]
Thanks for pointing this out, I forgot that this was a 3.7+ feature. I'd like to keep support for 3.6 as long as it's not EOL (which is at the end of this year). In this case, the import isn't actually required, so I'll just remove it.

**Comment by BastianZim** [comment]
Perfect, thank you for the clarification!
